name: CI
 
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Display information 1
        run: echo "Creating Mac and Windows build files at dist/$GITHUB_REF"
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'darwin/amd64, windows/amd64'
            package: ''
            name: 'backend'
            compress: 'false'
            dest: 'dist/$GITHUB_REF'
      - name: Display information 2
        run: echo ${{ format('{{"secret":"${{{{ secrets.GOLANG_UPLOAD_HEADER }}}}","version":"{0}"}', $GITHUB_REF) }}
      - name: Display information 3
        run: echo "Uploading Mac build file to identity server"
      - name: Upload Mac release
        id: upload-mac
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://identity.juicedbot.io/juiced/mac
          forms: ${{ format('{{"secret":"${{{{ secrets.GOLANG_UPLOAD_HEADER }}}}","version":"{0}"}', $GITHUB_REF) }}
          fileForms: '{"file":"dist/$GITHUB_REF/backend-darwin-amd64"}'
      - run: echo "Uploading Windows build file to identity server"
      - name: Upload Win release
        id: upload-win
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://identity.juicedbot.io/juiced/win
          forms: ${{ format('{{"secret":"${{{{ secrets.GOLANG_UPLOAD_HEADER }}}}","version":"{0}"}', $GITHUB_REF) }}
          fileForms: '{"file":"dist/$GITHUB_REF/backend-windows-amd64.exe"}'
