name: CI
 
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Extract Tag Name
        run: echo "##[set-output name=tag;]$(echo dist/${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Verify Tag Name
        run: echo '${{ steps.extract_tag.outputs.tag }}'
      - name: Extract Mac build file location
        run: echo "##[set-output name=mac;]$(echo dist/${GITHUB_REF#refs/tags/backend-darwin-amd64})"
        id: extract_mac
      - name: Verify Mac build file location
        run: echo '${{ steps.extract_mac.outputs.mac }}'
      - name: Extract Windows build file location
        run: echo "##[set-output name=win;]$(echo dist/${GITHUB_REF#refs/tags/}/backend-windows-amd64.exe)"
        id: extract_win
      - name: Verify Windows build file location
        run: echo '${{ steps.extract_win.outputs.win }}'
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'darwin/amd64, windows/amd64'
            package: ''
            name: 'backend'
            compress: 'false'
            dest: '${{ steps.extract_tag.outputs.tag }}'
      - name: Check forms value
        run: echo '{"secret":"${{ secrets.GOLANG_UPLOAD_HEADER }}","version":"${{ steps.extract_tag.outputs.tag }}"}'
      - name: Check fileForms value
        run: echo '{"file":"${{ steps.extract_mac.outputs.mac }}"}'
      - name: Upload Mac release
        id: upload-mac
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://identity.juicedbot.io/juiced/mac
          forms: '{"secret":"${{ secrets.GOLANG_UPLOAD_HEADER }}","version":"${{ steps.extract_tag.outputs.tag }}"}'
          fileForms: '{"file":"${{ steps.extract_mac.outputs.mac }}"}'
      - run: echo "Uploading Windows build file to identity server"
      - name: Upload Win release
        id: upload-win
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://identity.juicedbot.io/juiced/win
          forms: '{"secret":"${{ secrets.GOLANG_UPLOAD_HEADER }}","version":"${{ steps.extract_tag.outputs.tag }}"}'
          fileForms: '{"file":"${{ steps.extract_win.outputs.win }}"}'
